In [ ]:
print ('hello')

hello


In [ ]:
import numpy as np

In [ ]:
import numpy as np

a = np.zeros(10)

print(a)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [ ]:
import numpy as np

a = np.ones(10)

print(a)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [ ]:
import numpy as np

a = np.ones(10)*5

print(a)

[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


In [ ]:
import numpy as np

a = np.arange(10,51)

print(a)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


In [ ]:
import numpy as np

a = np.arange(10,51,2)

print(a)

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


In [ ]:
mat = np.arange(0,9).reshape(3,3)
print(mat)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
import numpy as np

a = np.ones((3,3))

print(a)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
import numpy as np

a = np.random.rand()

print(a)

0.09441524170673088


In [ ]:
import numpy as np

a = np.random.randint(1,1000,25)

print(a)

[870 586 957 412 112 867 636 998 605 262 156 676  68 958 339 751 947 561
 760 137 570 872 794 751 425]


In [ ]:
mat = np.arange(1,101).reshape(10,10)
print(mat)
mat1 = mat / 100
print(mat1)

[[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]]
[[0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1 ]
 [0.11 0.12 0.13 0.14 0.15 0.16 0.17 0.18 0.19 0.2 ]
 [0.21 0.22 0.23 0.24 0.25 0.26 0.27 0.28 0.29 0.3 ]
 [0.31 0.32 0.33 0.34 0.35 0.36 0.37 0.38 0.39 0.4 ]
 [0.41 0.42 0.43 0.44 0.45 0.46 0.47 0.48 0.49 0.5 ]
 [0.51 0.52 0.53 0.54 0.55 0.56 0.57 0.58 0.59 0.6 ]
 [0.61 0.62 0.63 0.64 0.65 0.66 0.67 0.68 0.69 0.7 ]
 [0.71 0.72 0.73 0.74 0.75 0.76 0.77 0.78 0.79 0.8 ]
 [0.81 0.82 0.83 0.84 0.85 0.86 0.87 0.88 0.89 0.9 ]
 [0.91 0.92 0.93 0.94 0.95 0.96 0.97 0.98 0.99 1.  ]]


In [ ]:
# это наша стартовая матрица
mat = np.arange(1,26).reshape(5,5)
print(mat)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [ ]:
# это наша стартовая матрица
mat = np.arange(1,26).reshape(5,5)
print(mat)
print(mat[3][4])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
20


In [ ]:
# это наша стартовая матрица
mat = np.arange(1,26).reshape(5,5)
print(mat)
print('-----------------')
print(mat[:][1])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
-----------------
[ 6  7  8  9 10]


In [ ]:
# это наша стартовая матрица
mat = np.arange(1,26).reshape(5,5)
print(mat)
print('-----------------')
print(mat[2:][2:])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
-----------------
[[21 22 23 24 25]]


In [ ]:
# это наша стартовая матрица
mat = np.arange(1,26).reshape(5,5)
print(mat)
print('-----------------')
print(mat[1:][2:])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
-----------------
[[16 17 18 19 20]
 [21 22 23 24 25]]


In [ ]:
# это наша стартовая матрица
mat = np.arange(1,26).reshape(5,5)
print(mat)
a = sum(mat)
b = sum(a)
print('-----------------')
print(b)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
-----------------
325


In [ ]:
# это наша стартовая матрица
mat = np.arange(1,26).reshape(5,5)
print(mat)
print('-----------------')
print(mat.std())

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
-----------------
7.211102550927978


In [ ]:
# это наша стартовая матрица
mat = np.arange(1,26).reshape(5,5)
print(mat)
a =sum(mat)
print('-----------------')
print(a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
-----------------
[55 60 65 70 75]
